# Generated by Django 2.2 on 2019-07-21 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardusers', '1097_auto_20190722_0547'),
        ('boardusers', '1097_auto_20190722_0548'),
    ]

    operations = [
    ]
