# Generated by Django 2.2 on 2019-07-21 01:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Like_And_Dislke',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('user_message_id', models.IntegerField()),
                ('status', models.IntegerField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 7, 21, 1, 46, 24, 832205, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='User_Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=300)),
                ('created_by', models.IntegerField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 7, 21, 1, 46, 24, 830655, tzinfo=utc))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 7, 21, 1, 46, 24, 830944, tzinfo=utc))),
                ('thump_up_count', models.IntegerField()),
                ('thump_down_count', models.IntegerField()),
            ],
        ),
    ]
