# Generated by Django 2.2 on 2019-07-21 05:47

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('boardusers', '0197_auto_20190721_1347'),
        ('boardmessages', '0148_auto_20190721_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='like_and_dislke',
            name='user_messages',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_messages', to='boardmessages.User_Message'),
        ),
        migrations.AddField(
            model_name='like_and_dislke',
            name='users',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='users', to='boardusers.Users'),
        ),
        migrations.AlterField(
            model_name='like_and_dislke',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 21, 5, 47, 14, 665682, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user_message',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 21, 5, 47, 14, 663292, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user_message',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 21, 5, 47, 14, 663484, tzinfo=utc)),
        ),
    ]
