# Generated by Django 2.2 on 2019-07-21 07:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('boardmessages', '0285_auto_20190721_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like_and_dislke',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 21, 7, 19, 32, 480482, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='like_and_dislke',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_message',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 21, 7, 19, 32, 479428, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user_message',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 21, 7, 19, 32, 479463, tzinfo=utc)),
        ),
    ]
