# Generated by Django 2.2 on 2019-07-21 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardmessages', '0295_auto_20190721_1523'),
        ('boardmessages', '0295_auto_20190721_1522'),
    ]

    operations = [
    ]
