# Generated by Django 2.2 on 2019-07-21 21:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('boardmessages', '1007_auto_20190722_0529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like_and_dislke',
            old_name='user_messages',
            new_name='User_Messages',
        ),
        migrations.RenameField(
            model_name='like_and_dislke',
            old_name='users',
            new_name='Users',
        ),
        migrations.AlterField(
            model_name='like_and_dislke',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 21, 21, 29, 50, 871852, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user_message',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 21, 21, 29, 50, 871239, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user_message',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 21, 21, 29, 50, 871275, tzinfo=utc)),
        ),
    ]
