# Generated by Django 2.2 on 2019-07-21 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardmessages', '1049_auto_20190722_0548'),
        ('boardmessages', '1049_auto_20190722_0547'),
    ]

    operations = [
    ]
